compressionLevel: mixed

enableGlobalCache: false

enableTransparentWorkspaces: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - arm64
  os:
    - current

yarnPath: .yarn/releases/yarn-4.0.2.cjs
